// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: register/registerUserRequest.proto

package register

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegisterUserSender_SendRegisterUserRequestSession_FullMethodName = "/RegisterUserSender/SendRegisterUserRequestSession"
)

// RegisterUserSenderClient is the client API for RegisterUserSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Send by 00.Gateway service to 01.Register service
type RegisterUserSenderClient interface {
	SendRegisterUserRequestSession(ctx context.Context, in *RegisterUserRequestRPC, opts ...grpc.CallOption) (*RegisterUserResponseRPC, error)
}

type registerUserSenderClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterUserSenderClient(cc grpc.ClientConnInterface) RegisterUserSenderClient {
	return &registerUserSenderClient{cc}
}

func (c *registerUserSenderClient) SendRegisterUserRequestSession(ctx context.Context, in *RegisterUserRequestRPC, opts ...grpc.CallOption) (*RegisterUserResponseRPC, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterUserResponseRPC)
	err := c.cc.Invoke(ctx, RegisterUserSender_SendRegisterUserRequestSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterUserSenderServer is the server API for RegisterUserSender service.
// All implementations must embed UnimplementedRegisterUserSenderServer
// for forward compatibility.
//
// Send by 00.Gateway service to 01.Register service
type RegisterUserSenderServer interface {
	SendRegisterUserRequestSession(context.Context, *RegisterUserRequestRPC) (*RegisterUserResponseRPC, error)
	mustEmbedUnimplementedRegisterUserSenderServer()
}

// UnimplementedRegisterUserSenderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegisterUserSenderServer struct{}

func (UnimplementedRegisterUserSenderServer) SendRegisterUserRequestSession(context.Context, *RegisterUserRequestRPC) (*RegisterUserResponseRPC, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRegisterUserRequestSession not implemented")
}
func (UnimplementedRegisterUserSenderServer) mustEmbedUnimplementedRegisterUserSenderServer() {}
func (UnimplementedRegisterUserSenderServer) testEmbeddedByValue()                            {}

// UnsafeRegisterUserSenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterUserSenderServer will
// result in compilation errors.
type UnsafeRegisterUserSenderServer interface {
	mustEmbedUnimplementedRegisterUserSenderServer()
}

func RegisterRegisterUserSenderServer(s grpc.ServiceRegistrar, srv RegisterUserSenderServer) {
	// If the following call pancis, it indicates UnimplementedRegisterUserSenderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegisterUserSender_ServiceDesc, srv)
}

func _RegisterUserSender_SendRegisterUserRequestSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequestRPC)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterUserSenderServer).SendRegisterUserRequestSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegisterUserSender_SendRegisterUserRequestSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterUserSenderServer).SendRegisterUserRequestSession(ctx, req.(*RegisterUserRequestRPC))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterUserSender_ServiceDesc is the grpc.ServiceDesc for RegisterUserSender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegisterUserSender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RegisterUserSender",
	HandlerType: (*RegisterUserSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRegisterUserRequestSession",
			Handler:    _RegisterUserSender_SendRegisterUserRequestSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "register/registerUserRequest.proto",
}
